apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: public-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: "{{ .Chart.Name }}"
