additionalArguments:
  - "--accesslog=true"
  - "--accesslog.format=json"
  - "--log.level=DEBUG"

deployment:
  replicas: 1

service:
  spec:
    loadBalancerIP: 20.166.201.127
  annotations:
    "service.beta.kubernetes.io/azure-load-balancer-resource-group": "mc_federicos-cluster_federicos-test-cluster_northeurope"
